In [1]:
import pandas as pd

In [3]:
df_a3cnf =pd.read_csv('A3NCF_Amazon_data_error_metrics.csv')
df_alfm =pd.read_csv('ALFM_Amazon_data_error_metrics.csv')

In [5]:
df_a3cnf.mean()

mae     0.948417
mse     1.420468
rmse    1.190213
dtype: float64

In [6]:
df_a3cnf.mean()

mae     0.948417
mse     1.420468
rmse    1.190213
dtype: float64

In [7]:
df_a3cnf

          mae       mse      rmse
0    0.966124  1.436639  1.198599
1    0.917933  1.262122  1.123442
2    0.916646  1.293396  1.137276
3    0.958315  1.460081  1.208338
4    0.915327  1.319409  1.148655
..        ...       ...       ...
564  0.874969  1.152740  1.073657
565  0.876276  1.142332  1.068799
566  0.901009  1.295975  1.138409
567  0.942690  1.392367  1.179986
568  0.868412  1.127190  1.061692

[569 rows x 3 columns]

In [8]:
df_a3cnf

          mae       mse      rmse
0    0.966124  1.436639  1.198599
1    0.917933  1.262122  1.123442
2    0.916646  1.293396  1.137276
3    0.958315  1.460081  1.208338
4    0.915327  1.319409  1.148655
..        ...       ...       ...
564  0.874969  1.152740  1.073657
565  0.876276  1.142332  1.068799
566  0.901009  1.295975  1.138409
567  0.942690  1.392367  1.179986
568  0.868412  1.127190  1.061692

[569 rows x 3 columns]